[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"
package_manager = "yarn"

[features]
resolution = true
seeds = true
skip-lint = false

[programs.devnet]
adrastia_chainlink_data_streams_feed_updater_solana = "pPcrVUVrQULhX2sF3HjYi36wiKJGsuwpAny17VTTmpj"
adrastia_chainlink_data_streams_feed_solana = "Et6bXECAiq9PH95uGwiAG4VyUUaD8JF4GZuCaduNBH9A"

[programs.localnet]
adrastia_chainlink_data_streams_feed_updater_solana = "pPcrVUVrQULhX2sF3HjYi36wiKJGsuwpAny17VTTmpj"
adrastia_chainlink_data_streams_feed_solana = "Et6bXECAiq9PH95uGwiAG4VyUUaD8JF4GZuCaduNBH9A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
